version: '3.0'

services:

  nginx:
    image: nginx
    container_name: ${APP_NAME}-nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_DEFAULT}
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app/:/var/www/html/
      - ../logs/:/var/log/nginx/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./php
    container_name: ${APP_NAME}-php
    volumes:
      - ../app/:/var/www/html/
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_PHPMYADMIN}
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - frontend
      - backend

networks:
  frontend:
    external:
      name: proxy_proxy
  backend:
